### ISSUE TITLE
Not able to save queue as playlist

### ISSUE THREAD

**Issue by flintstones-fred** [owntone/owntone-server#1707]
Using owntone docker image (`lscr.io/linuxserver/daapd:latest`) and not able to save queue as playlist. Here is the entry I see in the docker log - 
```
[2024-01-04 06:03:08] [  LOG]      web: Invalid playlist save directory '/playlists_2'
[2024-01-04 06:03:08] [  LOG]      web: JSON api request failed with error code 403 (/api/queue/save?name=test)
```
I came across [Issue 1485](https://github.com/owntone/owntone-server/issues/1485), but I still can't solve it. I am specifying the playlists directory using complete path. 

Steps that can help reproduce:
1. My docker-compose file (note that I tried this using both `/Playlists` and `/playlists_2` directories mentioned in the docker compose file with the same result. `/Playlist` is mounted on a samba share, whereas `/playlists_2` is part of the LXC filesystem:
```
version: "2.1"
services:
  daapd:
    image: lscr.io/linuxserver/daapd:latest
    container_name: owntone
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /root/owntone/config:/config
      - /root/owntone/playlists:/playlists_2
      - /mnt/USBHDD1/Media/Music:/music:ro
      - /mnt/USBHDD1/Media/Audiobooks:/Audiobooks:ro
      - /mnt/USBHDD1/Media/Playlists:/Playlists
      - /mnt/USBHDD1/Media/Podcasts:/Podcasts:ro
    restart: unless-stopped
```
 
2. My owntone.conf file relevant sections:
```
        # Directories to index
        directories = { "/music","/Audiobooks","/Playlists","/playlists_2" }

        # Allows creating, deleting and modifying m3u playlists in the library directories.
        # Only supported by the player web interface and some mpd clients
        # Defaults to being disabled.
        allow_modifying_stored_playlists = true

        # A directory in one of the library directories that will be used as the default
        # playlist directory. OwnTone creates new playlists in this directory if only
        # a playlist name is provided (requires "allow_modify_stored_playlists" set to true).
        default_playlist_directory = "/playlists_2"

        # By default OwnTone will - like iTunes - clear the playqueue if
        # playback stops. Setting clear_queue_on_stop_disable to true will keep
        # the playlist like MPD does. Note that some dacp clients do not show
        # the playqueue if playback is stopped.
        clear_queue_on_stop_disable = true

```

3. At the time of writing, I am using v28.8
